---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  new-line-at-end-of-file: disable
  empty-lines:
    max-end: 1
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
