networks:
  claudecluster-network:
    driver: bridge
    name: claudecluster-network

services:
  # Simple MCP Server Demo - Mock service to demonstrate architecture
  mcp-server-demo:
    image: node:18-alpine
    container_name: claudecluster-mcp-demo
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./demo-mcp-server.js:/app/server.js:ro
    command: ["node", "server.js"]
    environment:
      - PORT=3000
      - NODE_ENV=demo
    networks:
      - claudecluster-network
    restart: unless-stopped

  # Worker 1 Demo
  worker-1-demo:
    image: node:18-alpine
    container_name: claudecluster-worker-1-demo
    ports:
      - "3001:3001"
    working_dir: /app
    volumes:
      - ./demo-worker.js:/app/worker.js:ro
    command: ["node", "worker.js"]
    environment:
      - PORT=3001
      - WORKER_ID=worker-1
    networks:
      - claudecluster-network
    restart: unless-stopped

  # Worker 2 Demo
  worker-2-demo:
    image: node:18-alpine
    container_name: claudecluster-worker-2-demo
    ports:
      - "3002:3001"
    working_dir: /app
    volumes:
      - ./demo-worker.js:/app/worker.js:ro
    command: ["node", "worker.js"]
    environment:
      - PORT=3001
      - WORKER_ID=worker-2
    networks:
      - claudecluster-network
    restart: unless-stopped