name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 8 AM UTC
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  update-deps:
    name: Update Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '8.15.0'
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check for outdated dependencies
        id: outdated
        run: |
          OUTDATED=$(pnpm outdated --format json || echo "[]")
          echo "outdated_count=$(echo "$OUTDATED" | jq 'length')" >> $GITHUB_OUTPUT
          echo "::group::Outdated Dependencies"
          echo "$OUTDATED" | jq '.'
          echo "::endgroup::"

      - name: Update dependencies
        if: steps.outdated.outputs.outdated_count > 0
        run: |
          pnpm update
          pnpm install

      - name: Run tests after updates
        if: steps.outdated.outputs.outdated_count > 0
        run: |
          pnpm run lint
          pnpm run build
          pnpm run test

      - name: Create Pull Request
        if: steps.outdated.outputs.outdated_count > 0
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore: Weekly dependency updates"
          body: |
            This PR contains weekly dependency updates.
            
            - Updated ${{ steps.outdated.outputs.outdated_count }} dependencies
            - All tests are passing
            - Ready for review and merge
            
            Auto-generated by GitHub Actions.
          branch: chore/update-dependencies
          delete-branch: true
          labels: |
            dependencies
            automated